import React from "react";

const ExecutiveTemplate = ({ data, color }) => {
    if (!data) return null;

    return (
        <div className="w-[210mm] min-h-[297mm] bg-[#f8fafc] text-slate-900 shadow-2xl font-['Georgia'] p-0 flex">
            {/* Sidebar */}
            <aside className="w-[75mm] bg-slate-900 text-white p-10 flex flex-col gap-8">
                <div>
                    <h1 className="text-2xl font-bold mb-1 tracking-tight">{data.personal_info?.name}</h1>
                    <p className="text-xs uppercase tracking-[0.2em] text-slate-400">Executive Profile</p>
                </div>

                <div className="space-y-4">
                    <h2 className="text-sm font-bold uppercase tracking-widest pb-2 border-b border-slate-700" style={{ color: color }}>Contact</h2>
                    <ul className="text-[11px] space-y-3 text-slate-300">
                        {data.personal_info?.email && <li className="break-all"><strong>E:</strong> {data.personal_info.email}</li>}
                        {data.personal_info?.phone && <li><strong>P:</strong> {data.personal_info.phone}</li>}
                        {data.personal_info?.linkedin && <li className="break-all"><strong>L:</strong> {data.personal_info.linkedin}</li>}
                        {data.personal_info?.github && <li className="break-all"><strong>G:</strong> {data.personal_info.github}</li>}
                    </ul>
                </div>

                <div className="space-y-4">
                    <h2 className="text-sm font-bold uppercase tracking-widest pb-2 border-b border-slate-700" style={{ color: color }}>Core Skills</h2>
                    <ul className="text-[11px] space-y-2 text-slate-300">
                        {data.skills?.map((skill, i) => (
                            <li key={i} className="flex justify-between">
                                <span>{skill}</span>
                            </li>
                        ))}
                    </ul>
                </div>

                <div className="mt-auto pt-8">
                    <p className="text-[10px] text-slate-500 italic">Generated by CVForge AI</p>
                </div>
            </aside>

            {/* Main Content */}
            <main className="flex-1 bg-white p-12">
                <section className="mb-10">
                    <h2 className="text-lg font-bold uppercase tracking-widest mb-4 border-b pb-2" style={{ borderColor: color, color: color }}>Executive Summary</h2>
                    <p className="text-sm leading-relaxed text-slate-700 text-justify italic">
                        "{data.summary}"
                    </p>
                </section>

                <section className="mb-10">
                    <h2 className="text-lg font-bold uppercase tracking-widest mb-6 border-b pb-2" style={{ borderColor: color, color: color }}>Experience</h2>
                    <div className="space-y-8">
                        {data.experience?.map((exp, index) => (
                            <div key={index} className="relative pl-6 border-l-2 border-slate-100">
                                <div className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-white border-2" style={{ borderColor: color }}></div>
                                <div className="flex justify-between items-baseline mb-1">
                                    <h3 className="text-base font-bold text-slate-900">{exp.title}</h3>
                                    <span className="text-xs font-bold text-slate-500 uppercase">{exp.duration || exp.dates}</span>
                                </div>
                                <p className="text-sm font-semibold text-slate-600 mb-3">{exp.company}</p>
                                <ul className="text-[13px] space-y-2 text-slate-700 leading-snug">
                                    {Array.isArray(exp.description) ? (
                                        exp.description.map((item, idx) => (
                                            <li key={idx} className="flex gap-2">
                                                <span style={{ color: color }}>•</span>
                                                <span>{item}</span>
                                            </li>
                                        ))
                                    ) : (
                                        <li className="flex gap-2">
                                            <span style={{ color: color }}>•</span>
                                            <span>{exp.description}</span>
                                        </li>
                                    )}
                                </ul>
                            </div>
                        ))}
                    </div>
                </section>

                <section>
                    <h2 className="text-lg font-bold uppercase tracking-widest mb-6 border-b pb-2" style={{ borderColor: color, color: color }}>Education</h2>
                    <div className="space-y-6">
                        {data.education?.map((edu, index) => (
                            <div key={index}>
                                <div className="flex justify-between items-baseline">
                                    <h3 className="text-sm font-bold text-slate-900">{edu.degree}</h3>
                                    <span className="text-xs font-bold text-slate-500">{edu.year || edu.dates}</span>
                                </div>
                                <p className="text-sm text-slate-600">{edu.school}</p>
                            </div>
                        ))}
                    </div>
                </section>
            </main>
        </div>
    );
};

export default ExecutiveTemplate;
